dist: bionic
language: c

compiler:
  - gcc
  - clang

before_script:
  - travis_retry sudo apt-get -y install cmake pkg-config libgnutls28-dev zlib1g-dev libreadline-dev libcpputest-dev lcov

script:
  - ./tools/build-debian.sh test-patches
  - mkdir build && cd build
  - cmake -DBUILD_DOC=ON -DBUILD_MAN=ON -DBUILD_TESTS=ON -DCODE_COVERAGE=ON ..
  - make VERBOSE=1 -j$(nproc)
  - sudo make install
  - ctest -V

after_success:
  - weechat-relay-cli --help
  - weechat-relay-cli --license
  - weechat-relay-cli --version
  - lcov --directory . --capture --output-file coverage.info
  - lcov --remove coverage.info '/usr/*' --output-file coverage.info
  - lcov --list coverage.info
  - bash <(curl -s https://codecov.io/bash) -f coverage.info || echo 'Codecov error'

matrix:
  fast_finish: true
