= WeeChat Relay
:author: Sébastien Helleu
:email: flashcode@flashtux.org
:lang: en


image:https://travis-ci.org/weechat/weechat-relay.svg?branch=master["Build Status", link="https://travis-ci.org/weechat/weechat-relay"]
image:https://codecov.io/gh/weechat/weechat-relay/branch/master/graph/badge.svg["Code coverage", link="https://codecov.io/gh/weechat/weechat-relay"]

WeeChat Relay is a C library to communicate between WeeChat and a client using
the "weechat" relay protocol.

[IMPORTANT]
This library is under development, there is no stable version yet. +
*DO NOT USE IN PRODUCTION!*

Homepage: https://weechat.org/

== Features

* Communication between WeeChat and a client:
** from client to WeeChat: build and send commands, decode binary messages
   received from WeeChat
** from WeeChat to client: build and send binary messages.
* Command-line interface to the WeeChat Relay library (`weechat-relay-cli`),
  which can be used for tests, debug or in shell scripts.

== Install

=== Dependencies

Following packages are *required*:

* CMake
* GnuTLS
* GNU Readline (for `weechat-relay-cli`)
* zlib

=== Compile

* Installation in system directories (requires _root_ privileges):

----
$ mkdir build
$ cd build
$ cmake ..
$ make
$ sudo make install
----

* Installation in custom directory (for example your home):

----
$ mkdir build
$ cd build
$ cmake -DCMAKE_INSTALL_PREFIX=/path/to/directory ..
$ make
$ make install
----

=== Run tests

Following packages are *required* to compile tests:

* libcpputest-dev
* C++ compiler

Tests must be enabled when compiling WeeChat Relay:

----
$ cmake -DBUILD_TESTS=ON ..
----

They can be launched after compilation from the build directory:

----
$ ctest -V
----

== Command-line interface

The binary `weechat-relay-cli` can be used to debug communication between
a client and WeeChat relay.

For help:

----
weechat-relay-cli --help
----

== Copyright

Copyright (C) 2019-2020 Sébastien Helleu <flashcode@flashtux.org>

This file is part of WeeChat Relay.

WeeChat Relay is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 3 of the License, or
(at your option) any later version.

WeeChat Relay is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with WeeChat Relay.  If not, see <https://www.gnu.org/licenses/>.
