# SPDX-FileCopyrightText: 2019-2025 Sébastien Helleu <flashcode@flashtux.org>
#
# SPDX-License-Identifier: GPL-3.0-or-later

version = 1

[[annotations]]
path = [
    ".github/ISSUE_TEMPLATE/*",
    ".gitignore",
    "AUTHORS.md",
    "CHANGELOG.md",
    "CONTRIBUTING.md",
    "README.md",
    "UPGRADING.md",
    "debian-devel/**",
    "debian-stable/**",
    "tools/debian/patches/**",
    "weechat-relay.pc.in",
]
precedence = "override"
SPDX-FileCopyrightText = "2019-2025 Sébastien Helleu <flashcode@flashtux.org>"
SPDX-License-Identifier = "GPL-3.0-or-later"
