= weechat-relay-cli(1)
:doctype: manpage
:author: Sébastien Helleu
:email: flashcode@flashtux.org
:lang: en
:man manual: WeeChat Relay Manual
:man source: WeeChat Relay {revnumber}

== NAME

weechat-relay-cli - command line tool to test WeeChat relay connection

== SYNOPSIS

[verse]
*weechat-relay-cli* [-6|--ipv6] [-d|--debug] [-p|--port <port>] hostname
*weechat-relay-cli* [-h|--help]
*weechat-relay-cli* [-l|--license]
*weechat-relay-cli* [-v|--version]

== DESCRIPTION

weechat-relay-cli is a command line tool to test WeeChat relay connection.

It is used to connect to a running WeeChat, send commands and display binary
messages received from WeeChat.

== OPTIONS

*-6*, *--ipv6*::
    Connect using IPv6.

*-d*, *--debug*::
    Enable debug messages.  With two -d, display raw messages.

*-h*, *--help*::
    Display help and exit.

*-l*, *--license*::
    Display license and exit.

*-p*, *--port*::
    The port to connect to (default: 9000).

*-v*, *--version*::
    Display version and exit.

*hostname*::
    Hostname to connect to. A running WeeChat with a relay (type "weechat")
    must be setup on this host.

== COPYRIGHT

WeeChat Relay is written by Sébastien Helleu and contributors (complete list is
in the AUTHORS.adoc file).

Copyright (C) 2019-2021 {author}

WeeChat Relay is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 3 of the License, or
(at your option) any later version.

Please read the COPYING file for more information.

Web: https://weechat.org/

== SUPPORT / REPORTING BUGS

For help or a bug report: https://weechat.org/dev/support
