= weechat-relay-cli(1)
:doctype: manpage
:author: Sébastien Helleu
:email: flashcode@flashtux.org
:lang: en
:man manual: WeeChat Relay Manual
:man source: WeeChat Relay {revnumber}

== NAME

weechat-relay-cli - command line tool to test WeeChat relay connection

== SYNOPSIS

[verse]
*weechat-relay-cli* [--ipv4|--ipv6] [--command <command> [--command <command>...]] [--debug] [--port <port>] [--ssl] hostname
*weechat-relay-cli* --help
*weechat-relay-cli* --license
*weechat-relay-cli* --version

== DESCRIPTION

weechat-relay-cli is a command line tool to test WeeChat relay connection.

It is used to connect to a running WeeChat, send commands and display binary
messages received from WeeChat.

== OPTIONS

*-4*, *--ipv4*::
    Force connection using IPv4.

*-6*, *--ipv6*::
    Force connection using IPv6.

*-c*, *--command*::
    Send command once connected (this option can be given up to 16 times on
    command line).

*-d*, *--debug*::
    Enable debug messages.  With two --debug: display raw messages.

*-h*, *--help*::
    Display help and exit.

*-l*, *--license*::
    Display license and exit.

*-p*, *--port*::
    The port to connect to (default: 9000).

*-s*, *--ssl*::
    Use SSL/TLS to secure communication.

*-v*, *--version*::
    Display version and exit.

*hostname*::
    Hostname to connect to. A running WeeChat with a relay of type "weechat"
    must be setup on this host, with SSL if --ssl option is used.

== COPYRIGHT

WeeChat Relay is written by Sébastien Helleu and contributors (complete list is
in the AUTHORS.adoc file).

Copyright (C) 2019-2021 {author}

WeeChat Relay is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 3 of the License, or
(at your option) any later version.

Please read the COPYING file for more information.

Web: https://weechat.org/

== SUPPORT / REPORTING BUGS

For help or a bug report: https://weechat.org/dev/support
